version: '3.8'

services:
  frontend:
    image: souleymaabdenbi/soulaymaabdenbi-4twin1-g3-productflow:latest
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    image: souleymaabdenbi/soulaymaabdenbi-4twin1-g3-productflow:latest

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: devops
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
