version: "3.8"
services:
  backend:
    container_name: devops
    build:
      context: .
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/devops?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    depends_on:
      - mysqldb

  frontend:
    container_name: angular-app
    build:
      context: .
    ports:
      - "4200:80"
    restart: always

  mysqldb:
    image: "mysql:5.7"
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
