version: "3.8"
services:
  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/devops?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=amina
    restart: unless-stopped
    depends_on:
      - dbmysql

  dbmysql:
    image: "mysql:5.7"
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  angular-app:
    image: aminamami/angular:latest
    ports:
      - "4200:80"
    restart: always

volumes:
  db:
