version: '3.8'

services:
  # Frontend service
  frontend:
    image: souleymaabdenbi/soulaymaabdenbi-4twin1-g3-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  # Backend service
  backend:
    image: souleymaabdenbi/soulaymaabdenbi-4twin1-g3-productflow:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/devops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - app-network

  # MySQL service
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=devops
      - MYSQL_ROOT_PASSWORD=Souzem104*
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
