# Use the openjdk11 image from Docker Hub
FROM openjdk:11
# Expose the port of your Spring Boot application
EXPOSE 8080
# Add the JAR file to the container
 

# Run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]